# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official

# Workaround: AGP 9 built-in Kotlin + KSP source set conflict
android.disallowKotlinSourceSets=false

# WeatherAPI Key
WEATHER_API_KEY=b524165c039d4f90ae724953262609
